# Generated by Django 3.0.7 on 2020-06-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(default=0)),
                ('hsetype', models.CharField(max_length=2)),
                ('price', models.FloatField(default=0)),
                ('method', models.CharField(max_length=3)),
                ('datesold', models.DateField()),
                ('seller', models.CharField(max_length=252)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('postcode', models.CharField(max_length=4)),
                ('propertycount', models.IntegerField(default=0)),
                ('regionname', models.CharField(max_length=250)),
                ('distance', models.FloatField(default=0)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseprice_api.House')),
            ],
        ),
    ]
